### ISSUE TITLE
kedro install throws invalid command error

### ISSUE THREAD

**Issue by sbrugman** [quantumblacklabs/kedro-starter-pyspark-iris#18]
When running `kedro install` using this template from a new virtual environment on Windows 10, it throws the following error:
![image](https://user-images.githubusercontent.com/9756388/99151261-21deca00-269a-11eb-8db2-9f51102acc1f.png)

The reason for this is that [`wheel`](https://stackoverflow.com/a/44862371/470433) is not yet installed. The `requirements.txt` file is sorted, such that `wheel` is last. However, it is a dependency for other packages. Installing wheel manually can be used as workaround.

**Comment by lorenabalan** [comment]
Hi @sbrugman. I've not been able to reproduce this, and it looks like something `pip-compile` would definitely take care of. If you try `kedro install --build-reqs` does the problem persist?

**Comment by sbrugman** [comment]
Retested it in a new environment and the issue didn't come up again. Thanks for triaging the issue.
